/* Autogenerated with kurento-module-creator */

#include "FactoryRegistrar.hpp"

#include <FaceOverlayFilterImplFactory.hpp>
#include <FaceOverlayFilter.hpp>
#include <ImageOverlayFilterImplFactory.hpp>
#include <ImageOverlayFilter.hpp>
#include <ZBarFilterImplFactory.hpp>
#include <ZBarFilter.hpp>
#include <GStreamerFilterImplFactory.hpp>
#include <GStreamerFilter.hpp>
#include <OpenCVFilterImplFactory.hpp>
#include <OpenCVFilter.hpp>

extern "C" {

  const kurento::FactoryRegistrar *getFactoryRegistrar ();

}

const kurento::FactoryRegistrar *
getFactoryRegistrar ()
{
  static bool loaded = false;
  static std::map<std::string, std::shared_ptr<kurento::Factory>> factories;

  if (!loaded) {
    factories["FaceOverlayFilter"] = std::shared_ptr <kurento::Factory> (new kurento::FaceOverlayFilterImplFactory() );
    factories["ImageOverlayFilter"] = std::shared_ptr <kurento::Factory> (new kurento::ImageOverlayFilterImplFactory() );
    factories["ZBarFilter"] = std::shared_ptr <kurento::Factory> (new kurento::ZBarFilterImplFactory() );
    factories["GStreamerFilter"] = std::shared_ptr <kurento::Factory> (new kurento::GStreamerFilterImplFactory() );

    loaded = true;
  }

  static kurento::FactoryRegistrar factory (factories);
  return &factory;
}
