/* Autogenerated with kurento-module-creator */

#include "FaceOverlayFilterImpl.hpp"
#include "ImageOverlayFilterImpl.hpp"
#include "ZBarFilterImpl.hpp"
#include "GStreamerFilterImpl.hpp"
#include "OpenCVFilterImpl.hpp"
#include "CodeFound.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{

void dummyFilters ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<FaceOverlayFilter> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<ImageOverlayFilter> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<ZBarFilter> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<GStreamerFilter> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<OpenCVFilter> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<CodeFound> object;

    s.SerializeNVP (object);
  }
}

} /* kurento */
